### ISSUE TITLE
English version of doc

### ISSUE THREAD

**Issue by wongoo** [2SC1815J/md2pdf#3]
It's an interesting project, will it provide english version of doc?

**Comment by 2SC1815J** [comment]
Thank you for your interest. 
The English version is currently being translated. I'll let you know when it's done.

**Comment by 2SC1815J** [comment]
Sorry for the delayed response.
The translation to English has been done.

“Markdown to PDF Conversion Using AH Formatter” (PDF)
https://github.com/2SC1815J/md2pdf/raw/en/dist/all-en.pdf

Source code
https://github.com/2SC1815J/md2pdf/tree/en

**Comment by wongoo** [comment]
thanks very much！
